apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8500"
spec:
  selector:
    app: consul
  ports:
    - port: 8500
      targetPort: 8500
      name: http
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: consul-headless
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8500"
spec:
  clusterIP: None
  selector:
    app: consul
  ports:
    - port: 8300
      name: server
    - port: 8301
      name: serflan
    - port: 8302
      name: serfwan
    - port: 8600
      name: dns
