apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  serviceName: consul-headless
  replicas: {{ .Values.consul.replicas }}
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8500"
        prometheus.io/path: "/v1/agent/metrics"
    spec:
      containers:
        - name: consul
          image: "{{ .Values.consul.image.repository }}:{{ .Values.consul.image.tag }}"
          args:
            - "agent"
            - "-config-dir=/etc/consul"
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8300
              name: server
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: dns
          volumeMounts:
            - name: data
              mountPath: /consul/data
            - name: config
              mountPath: /etc/consul
          resources:
            {{- toYaml .Values.consul.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: consul-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.consul.storage.size }}
