# auth_enabled: false

# server:
#   http_listen_port: 3100
#   log_level: debug

# common:
#   instance_addr: 127.0.0.1
#   path_prefix: /loki
#   storage:
#     filesystem:
#       chunks_directory: /loki/chunks
#       rules_directory: /loki/rules
#   replication_factor: 1
#   ring:
#     kvstore:
#       store: inmemory

# query_range:
#   results_cache:
#     cache:
#       embedded_cache:
#         enabled: true
#         max_size_mb: 100

# schema_config:
#   configs:
#     - from: 2023-01-01
#       store: boltdb-shipper
#       object_store: filesystem
#       schema: v12
#       index:
#         prefix: index_
#         period: 24h

# ruler:
#   alertmanager_url: http://localhost:9093

# compactor:
#   working_directory: /tmp/loki/compactor
#   shared_store: filesystem


# limits_config:
#   enforce_metric_name: false
#   reject_old_samples: true
#   reject_old_samples_max_age: 168h

# chunk_store_config:
#   max_look_back_period: 0s

# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 168h

auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
