apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://outbrain_prometheus:9090
    isDefault: true

  - name: Fluent Bit
    type: loki
    access: proxy
    url: http://outbrain_fluent-bit:3100
