apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://outbrain_prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://outbrain_loki:3100
    version: 1
    isDefault: false
    jsonData:
      maxLines: 1000
    basicAuth: false
    editable: true
