apiVersion: 1

notifiers:
  - name: Email Alerts
    type: email
    uid: email_alerts
    org_id: 1
    is_default: true
    settings:
      addresses: your-email@domain.com

  - name: Slack Alerts
    type: slack
    uid: slack_alerts
    org_id: 1
    settings:
      url: https://hooks.slack.com/services/your-webhook-url
