global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'outbrain_consul'
    static_configs:
      - targets: ['outbrain_consul_node1:8500', 'outbrain_consul_node2:8500', 'outbrain_consul_node3:8500', 'outbrain_consul_node4:8500']

  - job_name: 'outbrain_fluent-bit'
    static_configs:
      - targets: ['outbrain_fluent-bit:2020']

  - job_name: 'outbrain_prometheus'
    static_configs:
      - targets: ['outbrain_prometheus:9090']

  - job_name: 'outbrain_cadvisor'
    static_configs:
      - targets: ['outbrain_cadvisor:8080']

  - job_name: 'outbrain_node_exporter'
    static_configs:
      - targets: ['outbrain_node_exporter:9100']
