global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'local-infra'
    instance: 'local-infra'

rule_files:
  - 'alerts/recording_rules.yml'
  - 'alerts/alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
      # Add AlertManager if you want to receive notifications
      # - alertmanager:9093

scrape_configs:
  - job_name: 'outbrain_consul'
    metrics_path: '/v1/agent/metrics'
    static_configs:
      - targets: ['outbrain_consul_node1:8500', 'outbrain_consul_node2:8500', 'outbrain_consul_node3:8500', 'outbrain_consul_node4:8500']

  - job_name: 'outbrain_fluent-bit'
    metrics_path: /api/v1/metrics/prometheus
    static_configs:
      - targets: ['outbrain_fluent-bit:2020']

  - job_name: 'outbrain_prometheus'
    static_configs:
      - targets: ['outbrain_prometheus:9090']

  - job_name: 'outbrain_cadvisor'
    static_configs:
      - targets: ['outbrain_cadvisor:8080']

  - job_name: 'outbrain_node-exporter'
    static_configs:
      - targets: ['outbrain_node-exporter:9100']

  - job_name: 'consul_services'
    consul_sd_configs:
      - server: 'localhost:8500'
        services:
          - 'cadvisor'
          - 'fluent-bit'
          - 'grafana'
          - 'loki'
          - 'node-exporter'
          - 'prometheus'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        action: keep
        regex: (node-exporter|fluent-bit|loki|cadvisor)
